import { expect } from "chai";
import { Board } from "../src/Board.mjs";
import { Tetromino } from "../src/Tetromino.mjs";

describe("Falling tetrominoes", () => {
  let board;
  beforeEach(() => {
    board = new Board(10, 6);
  });

  it("start from the top middle", () => {
    board.drop(Tetromino.T_SHAPE);

    expect(board.toString()).to.equalShape(
    `....T.....
     ...TTT....
     ..........
     ..........
     ..........
     ..........`
    );
  });

  it("moves left", () => {
    board.drop(Tetromino.T_SHAPE);
    board.moveLeft()
    expect(board.toString()).to.equalShape(
    `...T......
     ..TTT.....
     ..........
     ..........
     ..........
     ..........`
    );
  });

  it("moves left and down", () => {
    board.drop(Tetromino.T_SHAPE);
    board.moveLeft()
    board.tick()
    expect(board.toString()).to.equalShape(
    `..........
     ...T......
     ..TTT.....
     ..........
     ..........
     ..........`
    );
  });

  it("moves right", () => {
    board.drop(Tetromino.T_SHAPE);
    board.moveRight()
    expect(board.toString()).to.equalShape(
    `.....T....
     ....TTT...
     ..........
     ..........
     ..........
     ..........`
    );
  });

  it("moves right and down", () => {
    board.drop(Tetromino.T_SHAPE);
    board.moveRight()
    board.tick()
    expect(board.toString()).to.equalShape(
    `..........
     .....T....
     ....TTT...
     ..........
     ..........
     ..........`
    );
  });

  it("moves down and down", () => {
    board.drop(Tetromino.T_SHAPE);
    board.moveDown()
    board.tick()
    expect(board.toString()).to.equalShape(
    `..........
     ..........
     ....T.....
     ...TTT....
     ..........
     ..........`
    );
  });
});